Login page User Authentication - Has Error
Added the user login page for User with authentication. If The password and username match then user will be able login. But this has an exception which will be solved in next commit.
Exception: Missing user_loader or request_loader.